CREATE TABLE IF NOT EXISTS CLIENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_NUMBER VARCHAR2(20) NOT NULL,
    FULL_NAME VARCHAR2(30) NOT NULL,
    UNIQUE KEY DOCUMENT_NUMBER_UNIQUE (DOCUMENT_NUMBER)
);

CREATE TABLE IF NOT EXISTS APPOINTMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME NOT NULL,
    APPOINTMENT_DATE DATETIME NOT NULL ,
    PRICE DOUBLE,
    ID_CLIENT INT NOT NULL ,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID)
);