DROP TABLE IF EXISTS APPOINTMENT;
DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_NUMBER VARCHAR2(20) NOT NULL,
    FULL_NAME VARCHAR2(30) NOT NULL,
    UNIQUE KEY DOCUMENT_NUMBER_UNIQUE (DOCUMENT_NUMBER)
);

CREATE TABLE APPOINTMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME NOT NULL,
    APPOINTMENT_DATE DATETIME NOT NULL ,
    ID_CLIENT INT NOT NULL ,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID)
);