DROP TABLE IF EXISTS CITAS;
DROP TABLE IF EXISTS PERSONAS;

CREATE TABLE PERSONAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_DOCUMENTO VARCHAR2(20),
    NOMBRES VARCHAR2(30)
);

CREATE TABLE CITAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_CREACION DATETIME,
    FECHA_CITA DATETIME,
    ID_PERSONA INT,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS
);